# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180713_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pic',
            field=models.ImageField(default=12, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
