# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_link',
        ),
    ]
